[package]
name = "lunarity"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"
repository = "https://github.com/paritytech/lunarity"

[dependencies]
lunarity-ast = "0.1.0"
lunarity-lexer = "0.1.0"
lunarity-parser = "0.1.0"

[dev-dependencies]
toolshed = "0.4"
